name: 'GitHub Releases for Automated Package Publishing'
description: 'GitHub Action to validate and extract GitHub release information, used for automated package publishing.'
branding:
    icon: 'tag'
    color: 'green'
runs:
    using: 'node16'
    main: 'dist/index.js'
outputs:
    tag:
        description: 'Version tag to publish (if it exists)'
    version:
        description: 'Version to publish'
