name: 'GitHub Releases for Automated Package Publishing'
description: 'GitHub Action to validate and extract GitHub release information, used for automated package publishing.'
branding:
    icon: 'tag'
    color: 'green'
runs:
    using: 'node12'
    main: 'dist/index.js'
inputs:
    package-path:
        description: 'Path to package.json'
        default: './package.json'
outputs:
    tag:
        description: 'Version tag to publish (if it exists)'
    version:
        description: 'Version to publish'
