name: image-optimization
on:
    pull_request:
        paths:
            - '**.jpg'
            - '**.jpeg'
            - '**.png'
            - '**.webp'
    push:
        branches:
            - main
        paths:
            - '**.jpg'
            - '**.jpeg'
            - '**.png'
            - '**.webp'
    workflow_dispatch:
    schedule:
        - cron: '00 23 * * 0'
jobs:
    image-optimization:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Optimize images
              id: images
              uses: calibreapp/image-actions@main
              with:
                  compressOnly: ${{ github.event_name != 'pull_request' }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
            - name: Create pull request
              if: steps.images.outputs.markdown != ''
              uses: peter-evans/create-pull-request@v5
              with:
                  title: Optimizes images.
                  branch-suffix: timestamp
                  commit-message: Optimizes images.
                  body: ${{ steps.images.outputs.markdown }}
